'use client';
import {useState,useMemo,useEffect} from 'react';
import {toast} from 'sonner';
import {analyzePrint,fitShadeToVolume} from '@/lib/print-analysis.mjs';
function VolumeInput({axis,value,onChange}:{axis:string;value:number;onChange:(v:number)=>void}){const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);return <label className="volume-input">{axis}<div className="number-wrap"><input aria-label={`Build volume ${axis}`} type="number" min={60} max={1000} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{const n=Number(draft);if(Number.isFinite(n)&&n>=60&&n<=1000)onChange(n);else{setDraft(String(value));toast.error('Enter a build dimension from 60 to 1000 mm.');}}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><span>mm</span></div></label>;}
export default function PrintPanel({model,onChange}:{model:any;onChange:(p:any)=>void}){
 const [volume,setVolume]=useState([256,256,256]);
 const report=useMemo(()=>analyzePrint(model,volume),[model,volume]);
 return <><section><div className="section-label"><h2>Build volume</h2><span>mm</span></div><p className="mesh-note">Enter your printer’s usable X, Y and Z dimensions.</p><div className="volume-grid">{['X','Y','Z'].map((axis,i)=><VolumeInput key={axis} axis={axis} value={volume[i]} onChange={n=>setVolume(old=>old.map((v,j)=>i===j?n:v))}/>)}</div><dl className="base-specs"><div><dt>Model X / Y / Z</dt><dd>{report.size.map((n:number)=>n.toFixed(1)).join(' / ')} mm</dd></div><div><dt>In this orientation</dt><dd>{report.fits?'Fits build volume':'Exceeds build volume'}</dd></div></dl><button className="inspect-bottom" onClick={()=>{try{onChange(fitShadeToVolume(model.params,volume));toast.success('Sized to the build volume. Magnet dimensions stay fixed.');}catch(error){toast.error(error instanceof Error?error.message:'Could not fit the model.');}}}>Fit to build volume</button><p className="control-note">Scales the body and opening. Keeps the 5 mm bottom and exact magnet recess dimensions.</p></section><section className="control-section"><h2>Overhang review</h2><dl className="base-specs"><div><dt>Steepest downward face</dt><dd>{report.overhang.toFixed(0)}°</dd></div></dl><p className="mesh-note">Angles are measured from vertical, above the integrated bottom. {report.overhang>45?'Steep areas may need supports or a different print orientation.':'The surface has relatively gentle slopes; inspect it in your slicer.'}</p><p className="control-note">Geometry estimate only. It does not predict bridges, adhesion, temperature or your printer’s support settings.</p></section><section className="control-section"><h2>Shell & export</h2><button className="inspect-bottom" onClick={()=>onChange({texture:model.params.texture==='mesh'||model.params.texture==='woven'?'fluted':model.params.texture,wall:1.2})}>Use a 1.2 mm solid shell</button><p className="control-note">Removes perforations if present. Set perimeters and infill in your slicer. Spiral-vase compatibility is not tested.</p><p className="base-note">Preview the sliced toolpaths before printing. Flat magnet-pocket backing stays part of the exported STL.</p></section></>;
}
