export const SCULPTURE_PRESETS=[
 {name:'Soft swirl',description:'Broad smooth folds with a changing sweep and an open circular collar.',params:{shape:'flowing-folds',height:230,diameter:110,topDiameter:100,curve:20,foldCount:3,foldDepth:26,foldRotation:125,foldSway:14,foldVariation:15,foldSoftness:100,foldWaist:0,foldBottomBlend:55,foldTopBlend:35,texture:'smooth',twist:0,wall:1.2,socketDiameter:42,smoothBottom:3,smoothTop:2,lockTop:false}},
 {name:'Gentle waves',description:'A softly bowed cylinder with broad, slowly meandering waves.',params:{shape:'flowing-folds',height:210,diameter:130,topDiameter:140,curve:8,foldCount:4,foldDepth:10,foldRotation:15,foldSway:24,foldVariation:20,foldSoftness:100,foldWaist:0,foldBottomBlend:65,foldTopBlend:0,texture:'smooth',twist:0,wall:1.2,socketDiameter:42,smoothBottom:3,smoothTop:0,lockTop:false}},
 {name:'Ribbon spiral',description:'Alternating smooth ribbons and finely ribbed spiral panels, with a gentle waist.',params:{shape:'flowing-folds',height:250,diameter:100,topDiameter:75,curve:20,foldCount:3,foldDepth:26,foldRotation:150,foldSoftness:95,foldWaist:7,foldBottomBlend:55,foldTopBlend:35,texture:'fluted',textureDepth:.8,textureCount:72,twist:150,panelRibs:true,panelCoverage:65,panelRibCount:18,panelOffset:90,panelEdge:10,wall:1.2,socketDiameter:42,smoothBottom:2,smoothTop:1,lockTop:false}},
 {name:'Draped spiral',description:'Three broad, soft folds spiral into a smooth mounting rim.',params:{shape:'flowing-folds',height:240,diameter:120,topDiameter:110,curve:18,twist:0,texture:'smooth',textureDepth:0,foldCount:3,foldDepth:25,foldRotation:120,foldSoftness:85,foldBottomBlend:60,foldTopBlend:0,wall:1.2,socketDiameter:42,smoothBottom:10,smoothTop:2,lockTop:false}},
 {name:'Layered lantern',description:'Straight middle, rounded shoulders and vertical ribs. Add an inner diffuser below.',params:{shape:'rounded-cylinder',height:220,diameter:130,topDiameter:130,bodyDiameter:170,bottomShoulder:40,topShoulder:40,curve:0,twist:0,texture:'fluted',textureDepth:1.8,textureCount:36,wall:1.2,socketDiameter:42,smoothBottom:1,smoothTop:1,lockTop:false}},
 {name:'Banded square',description:'Straight square sides with broad horizontal panels and fine seams.',params:{shape:'cube',height:180,diameter:160,topDiameter:160,depthRatio:100,curve:0,twist:0,texture:'bands',ringDepth:.8,ringCount:7,ringSharpness:40,socketDiameter:42,wall:1.2,lockTop:true,smoothBottom:2,smoothTop:2}},
 {name:'Pleated cone',description:'Wide, low cone with fine vertical pleats.',params:{shape:'cone',height:95,diameter:230,topDiameter:70,curve:0,twist:0,texture:'pleated',textureDepth:2.5,textureCount:96,socketDiameter:202,smoothBottom:2,smoothTop:2}},
 {name:'Sculpted waist',description:'Two flared shoulders around a narrow center.',params:{shape:'sculpted',height:205,diameter:110,topDiameter:100,bulgeDepth:30,curve:0,twist:0,texture:'fluted',textureDepth:1.5,textureCount:64,socketDiameter:42,smoothBottom:3,smoothTop:3}},
 {name:'Horizontal lantern',description:'A broad lantern with shallow stacked rings.',params:{shape:'drum',height:155,diameter:170,topDiameter:170,curve:0,twist:0,texture:'rings',ringDepth:5,ringCount:12,ringSharpness:80,socketDiameter:42,smoothBottom:3,smoothTop:3}},
 {name:'Ripple orb',description:'Rounded body with a small number of deep rings.',params:{shape:'lantern',height:175,diameter:110,topDiameter:100,curve:8,twist:0,texture:'rings',ringDepth:7,ringCount:7,ringSharpness:35,socketDiameter:42,smoothBottom:4,smoothTop:4}},
 {name:'Asymmetric stack',description:'Three rounded lobes with an off-center sweep.',params:{shape:'stacked',height:240,diameter:100,topDiameter:100,bulgeDepth:38,stackCount:3,curve:0,twist:10,texture:'fluted',textureDepth:1.4,textureCount:48,leanX:18,asymmetricBulge:10,bulgeDirection:35,lobeDepth:3,socketDiameter:42,smoothBottom:3,smoothTop:3}}
];
