import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {BASE_DEFAULTS,BASE_SHAPES,BASE_PROFILES,BASE_TEXTURES,generateBase,validateBase,patchBase,matchShadeBase,baseSocketMax} from '../lib/base-model.mjs';
import {DEFAULTS,PRESETS,inspectModel} from '../lib/model.mjs';
import {createBinarySTL,stlFilename,stlDownloadUrl,createSTLResponse} from '../lib/stl-download.mjs';
function parse(buffer){const d=new DataView(buffer),n=d.getUint32(80,true),vertices=[],indices=[],map=new Map();assert.equal(buffer.byteLength,84+50*n);for(let i=0;i<n;i++)for(let j=0;j<3;j++){const xyz=[0,1,2].map(k=>d.getFloat32(84+i*50+12+j*12+k*4,true));assert.ok(xyz.every(Number.isFinite));const key=xyz.join(',');let id=map.get(key);if(id===undefined){id=vertices.length/3;map.set(key,id);vertices.push(...xyz);}indices.push(id);}return {positions:new Float32Array(vertices),indices:new Uint32Array(indices)};}
function zHits(m,x,y){const v=m.positions,f=m.indices,hits=[];for(let i=0;i<f.length;i+=3){const a=f[i]*3,b=f[i+1]*3,c=f[i+2]*3,den=(v[b+1]-v[c+1])*(v[a]-v[c])+(v[c]-v[b])*(v[a+1]-v[c+1]);if(Math.abs(den)<1e-10)continue;const u=((v[b+1]-v[c+1])*(x-v[c])+(v[c]-v[b])*(y-v[c+1]))/den,w=((v[c+1]-v[a+1])*(x-v[c])+(v[a]-v[c])*(y-v[c+1]))/den,t=1-u-w;if(u>=-1e-8&&w>=-1e-8&&t>=-1e-8)hits.push(u*v[a+2]+w*v[b+2]+t*v[c+2]);}return [...new Set(hits.map(z=>Math.round(z*1e4)/1e4))].sort((a,b)=>a-b);}
let count=0;for(const shape of BASE_SHAPES)for(const profile of BASE_PROFILES)for(const texture of BASE_TEXTURES){const p={...BASE_DEFAULTS,shape,profile,texture,twist:87,...(profile==='straight'?{diameter:180}:{})};assert.ok(inspectModel(generateBase(p,{segments:192,layers:40,pocketSegments:64})).valid,`${shape}/${profile}/${texture}`);count++;}
const exports=[];
for(const patch of [{height:6,topDiameter:60,diameter:60,socketDiameter:0,profile:'straight'},{shape:'rounded-square',texture:'wave',twist:90,depthRatio:70},{shape:'square',profile:'pedestal',socketDiameter:0,magnetRecesses:false},{shape:'hexagon',texture:'fluted',socketDiameter:152},{shape:'oval',depthRatio:70,socketDiameter:98}]){
 const p=validateBase({...BASE_DEFAULTS,...patch}),m=generateBase(p),buffer=createBinarySTL(p),parsed=parse(buffer);assert.ok(inspectModel({...m,...parsed}).valid,'re-imported base STL must be closed, manifold and outward wound');
 assert.equal(m.pockets.length,p.magnetRecesses?3:0);
 if(p.socketDiameter)assert.deepEqual(zHits(parsed,.113,.137),[],'holder socket passes through the base');else assert.deepEqual(zHits(parsed,.113,.137),[0,p.height],'closed center remains filled');
 for(const q of m.pockets){assert.deepEqual(zHits(parsed,q.center[0]+.137,q.center[1]+.117),[0,Math.round((p.height-3.3)*1e4)/1e4],'magnet recess has a closed bottom');const floors=[];for(let i=0;i<parsed.positions.length;i+=3){const x=parsed.positions[i],y=parsed.positions[i+1],z=parsed.positions[i+2];if(Math.abs(z-(p.height-3.3))<.00002&&Math.hypot(x-q.center[0],y-q.center[1])<4.16)floors.push([x,y]);}assert.ok(floors.length>=128);const xs=floors.map(v=>v[0]),ys=floors.map(v=>v[1]);assert.ok(Math.abs(Math.max(...xs)-Math.min(...xs)-8.3)<.00004);assert.ok(Math.abs(Math.max(...ys)-Math.min(...ys)-8.3)<.00004);assert.ok(p.height-3.3>=2.7-1e-8);}
 exports.push({shape:p.shape,height:p.height,opening:p.socketDiameter,magnets:m.pockets.length,bytes:buffer.byteLength,backing:p.height-3.3});
}
for(const shape of ['bell','cube','rounded-square','hexagon','oval']){const shade={...DEFAULTS,...PRESETS[shape],shape},base=matchShadeBase(BASE_DEFAULTS,shade),m=generateBase(base);assert.equal(base.topDiameter,shade.diameter);assert.equal(base.depthRatio,shade.depthRatio);for(let i=0;i<3;i++){const a=i*2*Math.PI/3,r=shade.diameter*Math.min(1,shade.depthRatio/100)/2-7;assert.ok(Math.hypot(m.pockets[i].center[0]-r*Math.cos(a),m.pockets[i].center[1]-r*Math.sin(a))<1e-8,'base magnets align with shade');}}
assert.equal(patchBase(BASE_DEFAULTS,{topDiameter:250}).diameter,250);assert.equal(patchBase(BASE_DEFAULTS,{profile:'straight'}).diameter,180);
assert.equal(patchBase(BASE_DEFAULTS,{topDiameter:60,depthRatio:70}).socketDiameter,14);assert.equal(baseSocketMax(BASE_DEFAULTS),152);
for(const patch of [{height:5},{socketDiameter:4},{socketDiameter:200},{magnetRecesses:'yes'},{topDiameter:250,diameter:190},{shape:'missing'}])assert.throws(()=>validateBase({...BASE_DEFAULTS,...patch}));
const res=createSTLResponse(new Request('https://test.local'+stlDownloadUrl(BASE_DEFAULTS)));assert.equal(res.status,200);assert.equal(res.headers.get('Content-Disposition'),`attachment; filename="${stlFilename(BASE_DEFAULTS)}"`);assert.deepEqual(new Uint8Array(await res.arrayBuffer()),new Uint8Array(createBinarySTL(BASE_DEFAULTS)));
const report={status:'passed',parameterCases:count,stlExports:exports,shadeMatchingCases:5};writeFileSync('.sites-runtime/base-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
